### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Dantys** [KabirKwatra/Google-Assistant-Discord-Bot#2]
Can you explain more specifically how to install the bot correctly, or rather, what needs to be done in the code?

**Comment by KabirKwatra** [comment]
You shouldn't need to edit any of the code to deploy.
The following environment variables are required when executing [the python script](https://github.com/KabirKwatra/Google-Assistant-Discord-Bot/blob/master/src/main.py) or when running a [linux container](https://github.com/KabirKwatra/Google-Assistant-Discord-Bot/blob/master/Dockerfile).
- `DISCORD_TOKEN` (see any discord bot tutorial)
- `GA_CREDENTIALS` (#1)
- `GA_DEVICE_ID` (#1)
- `GA_DEVICE_MODEL_ID` (#1)
- `GA_TOKEN` (#1)
